apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-k8s-cicd
  template:
    metadata:
      labels:
        app: jenkins-k8s-cicd
    spec:
      containers:
      - image: uhub.service.ucloud.cn/zzy0425/zzy0425:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-k8s-cicd
        env:
        - name: branch
          value: <BRANCH_NAME>
